apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: fedora-bootc
  namespace: bootc
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: quay.io/fedora/fedora-bootc:43
      importPolicy:
        importMode: Legacy
      name: "43"
      referencePolicy:
        type: Source
    - from:
        kind: DockerImage
        name: quay.io/fedora/fedora-bootc:44
      importPolicy:
        importMode: Legacy
      name: "44"
      referencePolicy:
        type: Source
