resources:
  - role.yaml
  - rolebinding.yaml
  - build.yaml
  - buildstrategy-buildah-high-performance.yaml
  - imagestream.yaml

  - build-mainline-kernel.yaml
  - build-f44.yaml

  - build-lemonade.yaml
