resources:
  - role.yaml
  - rolebinding.yaml
  - shipwright-build.yaml
  - shipwright-buildah-high-performance.yaml
  - imagestream.yaml

  - shipwright-build-mainline-kernel.yaml
  - shipwright-build-f44.yaml
