resources:
  - role.yaml
  - rolebinding.yaml
  - buildstrategy-buildah-high-performance.yaml
  - imagestream.yaml

  - build-f43.yaml
  - build-f44.yaml
  - build-mainline-kernel.yaml

  - build-lemonade.yaml
