apiVersion: shipwright.io/v1beta1
kind: Build
metadata:
  name: bootc-local-llm-mainline-kernel
  namespace: bootc
spec:
  source:
    type: Git
    git:
      url: https://github.com/kincl/bootc-local-llm.git
  strategy:
    name: buildah-high-performance
    kind: ClusterBuildStrategy
  paramValues:
    - name: dockerfile
      value: Containerfile.mainline-kernel
  output:
    image: image-registry.openshift-image-registry.svc:5000/bootc/bootc-local-llm:mainline-kernel
